### ISSUE TITLE
Create a test for basic intelmqctl commands

### ISSUE THREAD

**Issue by schacht-certat** [certtools/intelmq-vagrant#7]
- [x] intelmqctl start
- [x] intelmqctl stop
- [x] intelmqctl list bots
- [x] intelmqctl list bots --configured
- [x] intelmqctl list queues
- [x] intelmqctl check (can be checked for the return value)
- [x] intelmqctl upgrade-config (at least shouldn't raise an exception/return value check as well)
- [x] intelmqctl run with a bot having the scheduled run mode
- [x] intemqctl --type json list bots

**Comment by wagner-certat** [comment]
Other candidates are:
- `intelmqctl check` (can be checked for the return value)
- `intelmqctl upgrade-test` (at least shouldn't raise an exception/return value check as well)
- `intelmqctl run` with a bot having the `scheduled` run mode

**Comment by wagner-certat** [comment]
`intemqctl --type json list bots` is also important as I found out today. This line caused an exception for the command:
https://github.com/certtools/intelmq/blob/de1f77294bfe2af84942adda58176928487d27ff/intelmq/bots/parsers/shodan/parser.py#L591
Because sets are not serializable in JSON. (was fixed in certtools/intelmq@a6cd864ae)

**Comment by schacht-certat** [comment]
all the checks are implemented, for any additional checks, please create new issues
